### ISSUE TITLE
Sample file https://drive.google.com/uc?id=1rkbbl9zn-3M6qYljRNH-iJ_qOLcF5Q56 not available

### ISSUE THREAD

**Issue by frankchen121212** [Lizhen0909/LSHVec#4]
Hi, I'm trying to reproduce the tutorial jupyter notebook, but the sample .seq file is not available any more, would you please look into that? 

According to your jupyter notebook: the file is not there

https://drive.google.com/uc?id=1rkbbl9zn-3M6qYljRNH-iJ_qOLcF5Q56

Hope that you can help me, thank you

**Comment by Lizhen0909** [comment]
Sorry, the file was removed.

You may download it from http://ww2.cs.fsu.edu/~lshi/ActinoMock_Nanopore.seq.gz or https://www.amazon.com/clouddrive/share/eTIKYVLckXUCMnMQSpO8TCqZOwekmBrx23ZhMa3XO8d

refer to Dowload/Sample data section at https://github.com/Lizhen0909/PyLSHvec

**Comment by frankchen121212** [comment]
Thank you for your promp response, No problem from my side~
